name: Appium Test Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '4.1.x' # Ensure this matches your project's .NET version

    - name: Install OpenSSL 1.0 manually
      run: |
        wget https://www.openssl.org/source/old/1.0.2/openssl-1.0.2u.tar.gz
        tar -xzf openssl-1.0.2u.tar.gz
        cd openssl-1.0.2u
        ./config
        make
        sudo make install

    - name: Restore dependencies
      run: dotnet restore ./AppiumCSharp/AppiumCSharp.sln

    - name: Build the project
      run: dotnet build --configuration Release ./AppiumCSharp/AppiumCSharp.sln

    - name: Install Appium
      run: npm install -g appium

    - name: Start Appium server
      run: appium &

    - name: Run tests
      env:
        BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
        BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        BROWSERSTACK_APP_URL: ${{ secrets.BROWSERSTACK_APP_URL }}
      run: dotnet test --configuration Release --logger "trx;LogFileName=test_results.trx" ./AppiumCSharp/AppiumCSharp.sln
